### ISSUE TITLE
Colored by compensated vertical speed

### ISSUE THREAD

**Issue by scls19fr** [twpayne/igc2kmz#1]
Hello,

it will be nice to add a new kind of color for track.
Track "Colored by compensated vertical speed"

You need to calculate total energy (kinetic energy + potential energy)
see https://en.wikipedia.org/wiki/Variometer#Total_energy_compensation_in_theory

It's very useful for gliders pilots.

Kind regards

Sébastien

**Comment by twpayne** [comment]
Hi Sébastian,

This is a good idea, and should be fairly easy to implement. Could you send me an example glider IGC file and tell me the mass of the glider so I can work on an example? My email address is in my GitHub profile.

Cheers,
Tom

**Comment by twpayne** [comment]
I see that you've just posted http://pastebin.com/Kz9PYR1v from an ASW 28 (maximum take off weight 575kg) in #2 which is all I need.

**Comment by scls19fr** [comment]
I'm not real glider pilot anymore... just Condor.

I also noticed that there is a lot of gap. I wonder if that's not a Condor bug in there IGC ouput.

I can provide an Excel file from a binary Flight Track Record (.ftr) file if you want.

**Comment by twpayne** [comment]
Ah, OK, I think I see what is happening with the Condor-generated IGC files.

`igc2kmz` was designed to visualize paraglider flights. IGC files often have large position and altitude errors in them. `igc2kmz` tries to filter out these errors by removing [horizontal speeds greater than 40m/s](https://github.com/twpayne/igc2kmz/blob/master/igc2kmz/track.py#L52-53) and [vertical speeds greater than 30m/s](https://github.com/twpayne/igc2kmz/blob/master/igc2kmz/track.py#L55-56). These assumptions are clearly not valid for gliders. I'll relax them.

**Comment by scls19fr** [comment]
Ok. You can notice that there is 2 times more points in binary (and so excel file) than in igc file. You can also see in Excel file that I have 4 interesting data Qx, Qy, Qz, Qw (quaternion) https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation
A great improvement could be to replay flight in Google Earth.

**Comment by twpayne** [comment]
Google Earth isn't great at replaying flights. Doarama, on the other hand, is fantastic - and it runs in your web browser, so it's easy to share your flights with others. Have you seen it?
  http://www.doarama.com/view/2171

**Comment by scls19fr** [comment]
You might use something name this "climb (with energy compensation)"
and also use meter per second like climb
