### ISSUE TITLE
Leonardo Igc2Kmz not working

### ISSUE THREAD

**Issue by inairrishi** [twpayne/igc2kmz#10]
The attached igc file does not generate the kmz file. 

[2016-09-11-XCM-ELQ-01.igc.txt](https://github.com/twpayne/igc2kmz/files/468392/2016-09-11-XCM-ELQ-01.igc.txt)

Also the leonardo file http://www.paraglidingforum.com/leonardo/flight/1501562#

Both the  igc files are created using oudie 4.

**Comment by inairrishi** [comment]
By not working I mean the kmz file is 0 bytes.

**Comment by twpayne** [comment]
The IGC file needs to end with a `.igc` extension, not `.txt`. Try renaming the file and please re-open this issue if this does not solve the problem.

**Comment by inairrishi** [comment]
I appended the extension with .txt because git bug reporting system does not like .igc extension as attachment. The issue happens with .igc too.
Thx,R






On Tue, Sep 13, 2016 at 1:11 AM -0700, "Tom Payne" <notifications@github.com> wrote:












The IGC file needs to end with a .igc extension, not .txt. Try renaming the file and please re-open this issue if this does not solve the problem.

**Comment by twpayne** [comment]
What error do you get exactly when you run

```
$ bin/igc2kmz -i 2016-09-11-XCM-ELQ-01.igc -o 2016-09-11-XCM-ELQ-01.kmz
```

?

For me, igc2kmz generates a valid KMZ file, 247791 bytes long. There are a number of warnings about unrecognized F, J, and K records in the IGC file, but these can be safely ignored.

**Comment by inairrishi** [comment]
I haven't directly used the tool.i pick the kmz file from Leonardo's link. If you upload the igc and try to download the kmz you get a 0 byte file. That was my issue. I will try manually running the tool.Thx,R






On Tue, Sep 13, 2016 at 7:44 AM -0700, "Tom Payne" <notifications@github.com> wrote:












What error do you get exactly when you run

$ bin/igc2kmz -i 2016-09-11-XCM-ELQ-01.igc -o 2016-09-11-XCM-ELQ-01.kmz




?



For me, igc2kmz generates a valid KMZ file, 247791 bytes long. There are a number of warnings about unrecognized F, J, and K records in the IGC file, but these can be safely ignored.

**Comment by twpayne** [comment]
OK, it sounds like this is a bug in Leonardo's use of igc2kmz. Could you report it at https://github.com/leonardoxc/leonardoxc ?

**Comment by twpayne** [comment]
It looks like others are having similar problems with Leonardo, see http://www.paraglidingforum.com/viewtopic.php?p=p506913#p506913.

**Comment by inairrishi** [comment]
Yes I saw that too. I thought the post was too old to resurrect it. The manual igc2kmz works like you mentioned. It has warnings but it works.
Thx,R 

    On Wednesday, September 14, 2016 12:24 PM, Tom Payne <notifications@github.com> wrote:
 

 It looks like others are having similar problems with Leonardo, see http://www.paraglidingforum.com/viewtopic.php?p=p506913#p506913.—

**Comment by pmashurenko** [comment]
Issue still exists/appeared again.
When I'm trying to generate KMZ's for next flights I'm getting empty KMZ files.
http://www.paraglidingforum.com/leonardo/flight/1672175
http://www.paraglidingforum.com/leonardo/flight/1672169
http://www.paraglidingforum.com/leonardo/flight/1663984
http://www.paraglidingforum.com/leonardo/flight/1630890

**Comment by twpayne** [comment]
As written several times above, this is a bug in Leonardo, not igc2kmz.
