### ISSUE TITLE
Simple web frontend draft

### ISSUE THREAD

**Issue by cyberorg** [twpayne/igc2kmz#13]
Hi, thanks for the very useful tool for all paragliding people, I've created a simple php web frontend for igc2kmz, it is just a hack job, still posting here for your reference:

https://github.com/cyberorg/igc2kmz

README - Place this folder in Linux web server's document root, open http://localhost/igc2kmz/ Make sure uploaded_files folder is writable by web server user. See http://prime.cyberorg.co.in/igc2kmz for example.

**Comment by twpayne** [comment]
Thanks for the info!
