### ISSUE TITLE
igc2kmz (most detailed, bigger file) issue

### ISSUE THREAD

**Issue by shoaibaj** [twpayne/igc2kmz#15]
Hello,

Once you click to download the most detailed file, it downloads a 0 KB file. At first I thought it was user specific, so I tried several users and random tracklogs. All of them seem to have the same issue and the downloaded file is always of file size 0KB. Once it launches in google earth, it gives a no information in file error.

thank you.

Shoaib.

**Comment by twpayne** [comment]
This is a bug in Leonardo/paraglidingforum.com, not igc2kmz. See http://www.paraglidingforum.com/viewtopic.php?t=74112.

**Comment by shoaibaj** [comment]
Thanks for getting back so quickly! I dont have any pictures uploaded but I will see how to get it working at my end. thanks again, appreciate your amazing work!

Shoaib.
