### ISSUE TITLE
igc2kmz on Leonardo produces empty KML file error

### ISSUE THREAD

**Issue by chr15williams** [twpayne/igc2kmz#16]
Hi Tom,
I've noticed for a while now that your excellent igc2kmz part of Leonardo has not been functioning, specifically the "most detailed, bigger size" part.  I found it so useful when trying analyse where I went wrong on a flight.  Is there any hope of seeing it brought back to life?
Thank you for all your excellent work for the paragliding community which I hugely appreciate as a very mediocre pilot.
Best wishes,
Chris

**Comment by twpayne** [comment]
This is a bug in Leonardo. See #10 and #15.

**Comment by chr15williams** [comment]
Thanks Tom, Apologies for not spotting the previous reports.




On Wed, Apr 26, 2017 at 11:26 AM +0100, "Tom Payne" <notifications@github.com> wrote:












This is a bug in Leonardo. See #10 and #15.
