### ISSUE TITLE
Invalid C record

### ISSUE THREAD

**Issue by scls19fr** [twpayne/igc2kmz#2]
Hello,

I output from Condor Soaring an IGC file

    $ python bin/igc2kmz.py -i 20150509.igc -o 20150509.kmz

raises a warning

    WARNING:root:20150509.igc: invalid record 'C210615130110210615000003'

It will be nice if igc2kmz could support these C records and display both circuit (C records) and also track (B records).

An example of such a file
http://pastebin.com/Kz9PYR1v

Kind regards

**Comment by scls19fr** [comment]
Thanks for fixing this. But I don't see turn points defined in C record. Should I open an other issue ?

**Comment by twpayne** [comment]
Please re-open this one.

**Comment by scls19fr** [comment]
sorry I can't... https://github.com/twpayne/igc2kmz/issues/3
