### ISSUE TITLE
C records are not taken into account

### ISSUE THREAD

**Issue by scls19fr** [twpayne/igc2kmz#3]
C records are not taken into account when ouput a kmz file.

see https://github.com/twpayne/igc2kmz/issues/2

**Comment by twpayne** [comment]
Thanks for opening the issue! Will fix.

**Comment by scls19fr** [comment]
Thanks. I hope it will also work with several kmz file (same circuit but differents tracks (records) because differents gliders pilots.

**Comment by scls19fr** [comment]
Thanks a lot
