### ISSUE TITLE
Batch convert IGC to KMZ

### ISSUE THREAD

**Issue by scls19fr** [twpayne/igc2kmz#8]
Hi Tom (again),

it will be nice to provide a batch convert feature.

glob can help https://docs.python.org/2/library/glob.html

I have a directory with several IGC files. I would like to create a KMZ file (one per IGC file)

in such a case -o flag should be an output directory

Kind regards

**Comment by twpayne** [comment]
This can be done with a `for` loop in a shell script. `igc2kmz` doesn't need to support this functionality.
